=== Fabinout/tactical-fulcrum/towers/tower-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Tower",
  "type": "object",
  "definitions": {
    "classes": {
      "Enemy": {
        "type": "object",
        "properties": {
          "atk": {
            "type": "number",
            "minimum": 0
          },
          "def": {
            "type": "number",
            "minimum": 0
          },
          "exp": {
            "type": "number",
            "minimum": 0
          },
          "drop": {
            "type": "string",
            "enum": [
              null,
              "",
              "Blue key",
              "Blue potion",
              "Crimson key",
              "Drop of dream ocean",
              "Golden feather",
              "Guard card",
              "Guard deck",
              "Guard gem",
              "Guard piece",
              "Guard potion",
              "Green blue key",
              "Heavenly potion",
              "Life Crown",
              "Life potion",
              "Platinum key",
              "Power card",
              "Power deck",
              "Power gem",
              "Power piece",
              "Power potion",
              "Pulse book <Shield>",
              "Pulse book <Sword>",
              "Red potion",
              "Violet key",
              "Yellow key"
            ]
          },
          "hp": {
            "type": "number",
            "minimum": 1
          },
          "level": {
            "type": "number",
            "minimum": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "type": {
            "$ref": "#/definitions/enums/EnemyType"
          }
        },
        "additionalProperties": false,
        "required": ["atk", "def", "drop", "exp", "hp", "level", "name", "type"]
      },
      "Info": {
        "type": "object",
        "properties": {
          "atk": {
            "type": "number",
            "minimum": 0
          },
          "def": {
            "type": "number",
            "minimum": 0
          },
          "hp": {
            "type": "number",
            "minimum": 1
          },
          "bronzeMedal": {
            "type": "number",
            "minimum": 1
          },
          "silverMedal": {
            "type": "number",
            "minimum": 1
          },
          "goldMedal": {
            "type": "number",
            "minimum": 1
          },
          "platinumMedal": {
            "type": "number",
            "minimum": 1
          },
          "diamondMedal": {
            "type": "number",
            "minimum": 1
          },
          "moonMedal": {
            "type": "number",
            "minimum": 1
          }
        },
        "additionalProperties": false,
        "required": [
          "atk",
          "def",
          "hp",
          "bronzeMedal",
          "silverMedal",
          "goldMedal",
          "platinumMedal",
          "diamondMedal",
          "moonMedal"
        ]
      },
      "Item": {
        "type": "object",
        "properties": {
          "atk": {
            "type": "number",
            "minimum": 0
          },
          "def": {
            "type": "number",
            "minimum": 0
          },
          "hp": {
            "type": "number",
            "minimum": 0
          },
          "expMulAdd": {
            "type": "number",
            "minimum": 0
          },
          "expMulMul": {
            "type": "number",
            "minimum": 0
          },
          "hpMultAdd": {
            "type": "number",
            "minimum": 0
          },
          "hpMulMul": {
            "type": "number",
            "minimum": 0
          },
          "additionalProperties": false
        }
      },
      "Level": {
        "type": "object",
        "properties": {
          "atkAdd": {
            "type": "number",
            "minimum": 0
          },
          "atkMul": {
            "type": "number",
            "minimum": 0
          },
          "defAdd": {
            "type": "number",
            "minimum": 0
          },
          "defMul": {
            "type": "number",
            "minimum": 0
          },
          "hpAdd": {
            "type": "number",
            "minimum": 0
          },
          "hpMul": {
            "type": "number",
            "minimum": 0
          },
          "blueKey": {
            "type": "number",
            "minimum": 0
          },
          "crimsonKey": {
            "type": "number",
            "minimum": 0
          },
          "yellowKey": {
            "type": "number",
            "minimum": 0
          }
        },
        "additionalProperties": false,
        "required": ["atkAdd", "atkMul", "defAdd", "defMul", "hpAdd", "hpMul", "blueKey", "crimsonKey", "yellowKey"]
      },
      "Rooms": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "tiles": {
              "type": "array",
              "minItems": 15,
              "maxItems": 15,
              "items": {
                "type": "array",
                "minItems": 15,
                "maxItems": 15,
                "items": {
                  "oneOf": [
                    {
                      "$ref": "#/definitions/tiles/DoorTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/EnemyTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/EmptyTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/ItemTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/KeyTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/StaircaseTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/StartingPositionTile"
                    },
                    {
                      "$ref": "#/definitions/tiles/WallTile"
                    }
                  ]
                }
              }
            },
            "scores": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/classes/Score"
              }
            }
          },
          "additionalProperties": false,
          "required": ["name", "tiles", "scores"]
        }
      },
      "Score": {
        "type": "object",
        "properties": {
          "line": {
            "type": "number",
            "minimum": 0,
            "maximum": 14
          },
          "column": {
            "type": "number",
            "minimum": 0,
            "maximum": 14
          },
          "type": {
            "$ref": "#/definitions/enums/ScoreType"
          }
        },
        "additionalProperties": false,
        "required": ["line", "column", "type"]
      }
    },
    "enums": {
      "Color": {
        "type": "string",
        "enum": ["blue", "crimson", "greenBlue", "platinum", "violet", "yellow"]
      },
      "EnemyType": {
        "type": "string",
        "enum": ["Burgeoner", "Fighter", "Ranger", "Shadow", "Slasher"]
      },
      "ScoreType": {
        "type": "string",
        "enum": ["check", "crown", "star"]
      },
      "StaircaseDirection": {
        "type": "string",
        "enum": ["down", "up"]
      }
    },
    "tiles": {
      "DoorTile": {
        "type": "object",
        "properties": {
          "color": {
            "$ref": "#/definitions/enums/Color"
          },
          "type": {
            "type": "string",
            "const": "door"
          }
        },
        "additionalProperties": false,
        "required": ["color", "type"]
      },
      "EmptyTile": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "const": "empty"
          }
        },
        "additionalProperties": false,
        "required": ["type"]
      },
      "EnemyTile": {
        "type": "object",
        "properties": {
          "enemyType": {
            "$ref": "#/definitions/enums/EnemyType"
          },
          "level": {
            "type": "number",
            "minimum": 1
          },
          "type": {
            "type": "string",
            "const": "enemy"
          }
        },
        "additionalProperties": false,
        "required": ["enemyType", "level", "type"]
      },
      "ItemTile": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "enum": [
              "Blue potion",
              "Drop of dream ocean",
              "Golden feather",
              "Guard card",
              "Guard deck",
              "Guard gem",
              "Guard piece",
              "Guard potion",
              "Heavenly potion",
              "Life Crown",
              "Life potion",
              "Power card",
              "Power deck",
              "Power gem",
              "Power piece",
              "Power potion",
              "Pulse book <Shield>",
              "Pulse book <Sword>",
              "Red potion"
            ]
          },
          "type": {
            "type": "string",
            "const": "item"
          }
        },
        "additionalProperties": false,
        "required": ["name", "type"]
      },
      "KeyTile": {
        "type": "object",
        "properties": {
          "color": {
            "$ref": "#/definitions/enums/Color"
          },
          "type": {
            "type": "string",
            "const": "key"
          }
        },
        "additionalProperties": false,
        "required": ["color", "type"]
      },
      "StaircaseTile": {
        "type": "object",
        "properties": {
          "direction": {
            "$ref": "#/definitions/enums/StaircaseDirection"
          },
          "type": {
            "type": "string",
            "const": "staircase"
          }
        },
        "additionalProperties": false,
        "required": ["direction", "type"]
      },
      "StartingPositionTile": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "const": "startingPosition"
          }
        },
        "additionalProperties": false,
        "required": ["type"]
      },
      "WallTile": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "const": "wall"
          }
        },
        "additionalProperties": false,
        "required": ["type"]
      }
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "value": "tower-schema.json"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "info": {
      "type": "object",
      "items": {
        "$ref": "#/definitions/classes/Info"
      }
    },
    "enemies": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/classes/Enemy"
      }
    },
    "items": {
      "type": "object",
      "properties": {
        "Blue potion": {
          "$ref": "#/definitions/classes/Item"
        },
        "Drop of dream ocean": {
          "$ref": "#/definitions/classes/Item"
        },
        "Golden feather": {
          "$ref": "#/definitions/classes/Item"
        },
        "Guard card": {
          "$ref": "#/definitions/classes/Item"
        },
        "Guard deck": {
          "$ref": "#/definitions/classes/Item"
        },
        "Guard gem": {
          "$ref": "#/definitions/classes/Item"
        },
        "Guard piece": {
          "$ref": "#/definitions/classes/Item"
        },
        "Guard potion": {
          "$ref": "#/definitions/classes/Item"
        },
        "Green blue key": {
          "$ref": "#/definitions/classes/Item"
        },
        "Heavenly potion": {
          "$ref": "#/definitions/classes/Item"
        },
        "Life Crown": {
          "$ref": "#/definitions/classes/Item"
        },
        "Life potion": {
          "$ref": "#/definitions/classes/Item"
        },
        "Power card": {
          "$ref": "#/definitions/classes/Item"
        },
        "Power deck": {
          "$ref": "#/definitions/classes/Item"
        },
        "Power gem": {
          "$ref": "#/definitions/classes/Item"
        },
        "Power piece": {
          "$ref": "#/definitions/classes/Item"
        },
        "Power potion": {
          "$ref": "#/definitions/classes/Item"
        },
        "Pulse book <Shield>": {
          "$ref": "#/definitions/classes/Item"
        },
        "Pulse book <Sword>": {
          "$ref": "#/definitions/classes/Item"
        },
        "Red potion": {
          "$ref": "#/definitions/classes/Item"
        }
      },
      "additionalProperties": false
    },
    "levels": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/classes/Level"
      }
    },
    "rooms": {
      "type": "object",
      "properties": {
        "standard": {
          "$ref": "#/definitions/classes/Rooms"
        },
        "nexus": {
          "$ref": "#/definitions/classes/Rooms"
        }
      },
      "additionalProperties": false,
      "required": ["nexus", "standard"]
    }
  },
  "additionalProperties": false,
  "required": ["$schema", "name", "info", "enemies", "items", "levels", "rooms"]
}

=== Fabinout/tactical-fulcrum/data/1-2.json
{
  "$schema": "tower-schema.json",
  "name": "Chapter 1-2 Tactical tower NEW",
  "info": {
    "atk": 50,
    "def": 0,
    "hp": 1000,
    "bronzeMedal": 0,
    "silverMedal": 0,
    "goldMedal": 0,
    "platinumMedal": 0,
    "diamondMedal": 0,
    "moonMedal": 0
  },
  "enemies": [
    {
      "type": "Burgeoner",
      "level": 5,
      "name": "Junior Burgeoner",
      "hp": 2500,
      "atk": 100,
      "def": 0,
      "exp": 20,
      "drop": ""
    },
    {
      "type": "Burgeoner",
      "level": 9,
      "name": "Burgeoner",
      "hp": 3000,
      "atk": 300,
      "def": 0,
      "exp": 50,
      "drop": ""
    },
    {
      "type": "Burgeoner",
      "level": 30,
      "name": "Master Burgeoner",
      "hp": 18000,
      "atk": 1000,
      "def": 300,
      "exp": 470,
      "drop": ""
    },
    {
      "type": "Fighter",
      "level": 1,
      "name": "Junior Fighter",
      "hp": 200,
      "atk": 100,
      "def": 0,
      "exp": 2,
      "drop": "Guard piece"
    },
    {
      "type": "Fighter",
      "level": 3,
      "name": "Fighter",
      "hp": 300,
      "atk": 200,
      "def": 0,
      "exp": 5,
      "drop": "Guard piece"
    },
    {
      "type": "Fighter",
      "level": 6,
      "name": "Elder Fighter",
      "hp": 600,
      "atk": 300,
      "def": 100,
      "exp": 10,
      "drop": "Guard gem"
    },
    {
      "type": "Fighter",
      "level": 11,
      "name": "Great Fighter",
      "hp": 1000,
      "atk": 400,
      "def": 200,
      "exp": 18,
      "drop": "Guard gem"
    },
    {
      "type": "Fighter",
      "level": 17,
      "name": "Fine Fighter",
      "hp": 2000,
      "atk": 700,
      "def": 300,
      "exp": 30,
      "drop": "Guard potion"
    },
    {
      "type": "Fighter",
      "level": 36,
      "name": "General Fighter",
      "hp": 5500,
      "atk": 1200,
      "def": 600,
      "exp": 70,
      "drop": "Guard card"
    },
    {
      "type": "Ranger",
      "level": 3,
      "name": "Junior Ranger",
      "hp": 200,
      "atk": 100,
      "def": 0,
      "exp": 2,
      "drop": "Red potion"
    },
    {
      "type": "Ranger",
      "level": 6,
      "name": "Ranger",
      "hp": 200,
      "atk": 200,
      "def": 100,
      "exp": 5,
      "drop": "Red potion"
    },
    {
      "type": "Ranger",
      "level": 13,
      "name": "Elder Ranger",
      "hp": 800,
      "atk": 300,
      "def": 100,
      "exp": 10,
      "drop": "Blue potion"
    },
    {
      "type": "Ranger",
      "level": 16,
      "name": "Great Ranger",
      "hp": 800,
      "atk": 600,
      "def": 100,
      "exp": 18,
      "drop": "Blue potion"
    },
    {
      "type": "Ranger",
      "level": 19,
      "name": "Fine Ranger",
      "hp": 800,
      "atk": 800,
      "def": 200,
      "exp": 30,
      "drop": "Blue potion"
    },
    {
      "type": "Ranger",
      "level": 23,
      "name": "Master Ranger",
      "hp": 2000,
      "atk": 1000,
      "def": 100,
      "exp": 47,
      "drop": "Life potion"
    },
    {
      "type": "Ranger",
      "level": 32,
      "name": "General Ranger",
      "hp": 2000,
      "atk": 1600,
      "def": 200,
      "exp": 70,
      "drop": "Life potion"
    },
    {
      "type": "Ranger",
      "level": 36,
      "name": "Legendary Ranger",
      "hp": 3000,
      "atk": 2200,
      "def": 400,
      "exp": 100,
      "drop": "Heavenly potion"
    },
    {
      "type": "Shadow",
      "level": 3,
      "name": "Junior Shadow",
      "hp": 300,
      "atk": 200,
      "def": 0,
      "exp": 4,
      "drop": "Yellow key"
    },
    {
      "type": "Shadow",
      "level": 8,
      "name": "Shadow",
      "hp": 500,
      "atk": 300,
      "def": 100,
      "exp": 16,
      "drop": "Blue key"
    },
    {
      "type": "Shadow",
      "level": 14,
      "name": "Elder Shadow",
      "hp": 600,
      "atk": 700,
      "def": 100,
      "exp": 36,
      "drop": "Crimson key"
    },
    {
      "type": "Shadow",
      "level": 22,
      "name": "Great Shadow",
      "hp": 1200,
      "atk": 1200,
      "def": 200,
      "exp": 64,
      "drop": "Violet key"
    },
    {
      "type": "Shadow",
      "level": 50,
      "name": "Fine Shadow",
      "hp": 5000,
      "atk": 3000,
      "def": 0,
      "exp": 200,
      "drop": "Yellow key"
    },
    {
      "type": "Shadow",
      "level": 60,
      "name": "Master Shadow",
      "hp": 7000,
      "atk": 4000,
      "def": 100,
      "exp": 250,
      "drop": "Blue key"
    },
    {
      "type": "Slasher",
      "level": 1,
      "name": "Junior Slasher",
      "hp": 100,
      "atk": 200,
      "def": 0,
      "exp": 2,
      "drop": "Power piece"
    },
    {
      "type": "Slasher",
      "level": 3,
      "name": "Slasher",
      "hp": 200,
      "atk": 300,
      "def": 0,
      "exp": 5,
      "drop": "Power piece"
    },
    {
      "type": "Slasher",
      "level": 6,
      "name": "Elder Slasher",
      "hp": 400,
      "atk": 500,
      "def": 0,
      "exp": 10,
      "drop": "Power gem"
    },
    {
      "type": "Slasher",
      "level": 11,
      "name": "Great Slasher",
      "hp": 800,
      "atk": 600,
      "def": 100,
      "exp": 18,
      "drop": "Power gem"
    },
    {
      "type": "Slasher",
      "level": 17,
      "name": "Fine Slasher",
      "hp": 1000,
      "atk": 1000,
      "def": 200,
      "exp": 30,
      "drop": "Power potion"
    }
  ],
  "items": {},
  "levels": [
    {
      "atkAdd": 0,
      "atkMul": 0,
      "defAdd": 0,
      "defMul": 0,
      "hpAdd": 10,
      "hpMul": 0,
      "blueKey": 0,
      "crimsonKey": 0,
      "yellowKey": 0
    }
  ],
  "rooms": {
    "standard": [
      {
        "name": "1F-Chaotic layer",
        "tiles": [
          [
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            }
          ],
          [
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            }
          ],
          [
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            }
          ],
          [
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            }
          ],
          [
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
              "type": "empty"
            },
            {
